/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.6
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PetIdUploadImageBody model module.
 * @module model/PetIdUploadImageBody
 * @version 1.0.6
 */
export class PetIdUploadImageBody {
  /**
   * Constructs a new <code>PetIdUploadImageBody</code>.
   * @alias module:model/PetIdUploadImageBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PetIdUploadImageBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PetIdUploadImageBody} obj Optional instance to populate.
   * @return {module:model/PetIdUploadImageBody} The populated <code>PetIdUploadImageBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PetIdUploadImageBody();
      if (data.hasOwnProperty('additionalMetadata'))
        obj.additionalMetadata = ApiClient.convertToType(data['additionalMetadata'], 'String');
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'Blob');
    }
    return obj;
  }
}

/**
 * Additional data to pass to server
 * @member {String} additionalMetadata
 */
PetIdUploadImageBody.prototype.additionalMetadata = undefined;

/**
 * file to upload
 * @member {Blob} file
 */
PetIdUploadImageBody.prototype.file = undefined;

